googledatastudio/community-connectors

community-connectors/github/CustomCache.js
community-connectors/github/main.js

Adding a cache for the GitHub.com community connector.

Added caching to GitHub connector.

---

community-connectors/meetup/src/Connector.gs
community-connectors/meetup/src/schema.gs
community-connectors/meetup/test/Connector.test.js

Added Manual Attendance Count for when you manually enter the amount of people that have come to your event.
Changed the URL parameters to look at upcoming and past events as opposed to the default of just upcoming events.

Meetup Connector Update

---

.gitignore

https://github.com/harthur/brain/issues/25#issuecomment-19510188

Simplify gitignore.

---

community-connectors/star-wars-api/appsscript.json
community-connectors/star-wars-api/main.js

I have built a community connector that accesses the Star Wars API (https://swapi.co/). I would like to contribute it to the open source community connector repository.

Added Star Wars API connector

---

.gitignore
community-connectors/sfo-data/AbstractConnector.js
community-connectors/sfo-data/Connector.js
community-connectors/sfo-data/api.js
community-connectors/sfo-data/appsscript.json
community-connectors/sfo-data/schema.js

created a connector for the dataset located at [sf open data](https://data.sfgov.org/Transportation/Air-Traffic-Passenger-Statistics/rkru-6vcg) with air traffic passenger statistics.

edited gitignore and added a connector for sfo data

---

github/main.js

Make organization and repository be configurable.

Added parameterization to GitHub connector.

---

.gitignore
kaggle/README.md
kaggle/src/.clasp.json
package.json
yarn.lock

I updated the Readme with the managed deployment link and added clasp as a dependencies to make it easier to managed the deployments.

Updated managed deployment for the kaggle connector.

---

google-fit/src/Connector.js
google-fit/src/GoogleFit.js
google-fit/src/appsscript.json

- Added comments and updated some formatting
- Removed some old code
- Removed dependency on OAuth2 library from appscript.json

Minor updates to Google Fit connector

---

README.md

Remove old community-connectors/ folder

---

github/main.js

fixed problem with `this`.

---

community-connectors/openweathermap-current/appsscript.json
community-connectors/openweathermap-current/main.js

This is a connector for the OpenWeatherMap API Current Weather.

Add OpenWeatherMap Current Weather Connector

---

community-connectors/where-the-iss-at/appsscript.json
community-connectors/where-the-iss-at/main.js

This is a connector for the Where the ISS at? API, returning real-time positional data for the International Space Station.

Add ISS Connector

---

community-connectors/openweathermap-forecast/appsscript.json
community-connectors/openweathermap-forecast/main.js

This is a connector for the OpenWeatherMap API 5-Day Forecast.

Add OpenWeatherMap Forecast Connector

---

community-connectors/nytimes-top-stories/appsscript.json
community-connectors/nytimes-top-stories/main.js

This is a connector for the New York Times Top Stories API.

Add NY Times Top Stories Connector

---

community-connectors/nytimes-most-popular/appsscript.json
community-connectors/nytimes-most-popular/main.js

This is a connector for the New York Times Most Popular Stories API.

Add NY Times Most Popular Connector

---

community-connectors/nasa-apod/appsscript.json
community-connectors/nasa-apod/main.js

This is a connector to the NASA Astronomy Photo of the Day API.

Add NASA APOD Connector

---

community-connectors/bart-realtime-departures/appsscript.json
community-connectors/bart-realtime-departures/main.js

This is a connector for the Bay Area Rapid Transit API to retrieve real-time departures info.

Add BART Connector

---

google-fit/src/Connector.js
google-fit/src/GoogleFit.js

Adding Heart Rate metrics (without factoring away repetitious code...).
Fixes #102.

Adding Google Fit Heart Rate metric

---

chrome-ux-report/src/Code.js

Switched from the old `DS_USER` format to using the Apps Script Bean.

Migrate to better error handling

---

README.md

- Adds a Travis badge to the repo ([Preview](https://github.com/googledatastudio/community-connectors/blob/effd0cad019e0525fad3d57c70a79e274b054492/README.md)).
- Updates README title to reflect repo contents (vs other repos)
CC: @diminishedprime

docs: Add Travis badge to README

---

kaggle/src/connector.js
senuto/src/appsscript.json

Updated the code as per review comments

Update authtype config and schema to use DataStudioApp

---

gke-usage-metering/src/main.ts

The accepted format should be separated by ".", not ":"

Fix the hint text

---

gke-usage-metering/src/gkeUsageMetering.ts

The regex patterns should be declared using new RegExp()

Fix regex bug

---

chrome-ux-report/README.md

Clarify that this connector code isn't necessarily mirroring production
cc @minhaz

Update CrUX connector README
